DROP TABLE IF EXISTS order_shipping_status;
DROP TABLE IF EXISTS shipping_order;
CREATE TABLE shipping_order (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    order_id VARCHAR(100) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL,
    product_id VARCHAR(100) NOT NULL,
    OUTSTANDING_AMT DECIMAL(10,2) NOT NULL,
    TOTAL_AMT DECIMAL(10,2) NOT NULL,
    status VARCHAR(50) NOT NULL,  -- CREATED / INVENTORY_RESERVED / PAYMENT_COMPLETED / SHIPPED / CANCELLED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE order_shipping_status (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    shipping_id VARCHAR(100),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_shipping_orders
        FOREIGN KEY (shipping_id) REFERENCES shipping_order(id)
);

