DROP TABLE IF EXISTS ORDERS;
DROP TABLE IF EXISTS orders_status_details;
CREATE TABLE "ORDERS" (
    id VARCHAR(100) NOT NULL PRIMARY KEY,
    user_id VARCHAR(100) NOT NULL,
    product_id VARCHAR(100) NOT NULL,
    transaction_id VARCHAR(100),
    shipping_id VARCHAR(100),
    quantity INT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    status VARCHAR(50) NOT NULL,  -- CREATED / INVENTORY_RESERVED / PAYMENT_COMPLETED / SHIPPED / CANCELLED
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE orders_status_details (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    reason VARCHAR(200),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    order_id VARCHAR(100),
    CONSTRAINT fk_orders
        FOREIGN KEY (order_id) REFERENCES orders(id)
);
